"""Report generation: a self-contained interactive HTML analytics dashboard
and a polished PDF summary report, produced from the same figures/data the
Streamlit GUI renders live.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List

import plotly.io as pio
from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Image as RLImage,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from core.visualizations import fig_to_png_bytes

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>{title} — Analytics Report</title>
<style>
  body {{ background:#0f0f1a; color:#e6e6f0; font-family: 'Segoe UI', Arial, sans-serif; margin:0; padding:0 0 60px 0; }}
  header {{ background: linear-gradient(135deg,#312e81,#7c3aed 60%,#db2777); padding:48px 40px; }}
  header h1 {{ margin:0; font-size:2.4rem; }}
  header p {{ opacity:0.85; margin-top:8px; }}
  .grid {{ display:grid; grid-template-columns: repeat(auto-fit, minmax(420px,1fr)); gap:24px; padding:32px 40px; }}
  .card {{ background:#181829; border:1px solid #2b2b45; border-radius:16px; padding:16px; box-shadow:0 8px 24px rgba(0,0,0,0.35); }}
  .metrics {{ display:grid; grid-template-columns: repeat(auto-fit, minmax(180px,1fr)); gap:16px; padding:0 40px 8px 40px; }}
  .metric {{ background:#181829; border-radius:14px; padding:18px; text-align:center; border:1px solid #2b2b45; }}
  .metric .value {{ font-size:1.6rem; font-weight:700; color:#c4b5fd; }}
  .metric .label {{ font-size:0.85rem; opacity:0.7; margin-top:4px; }}
  section.text-block {{ padding: 8px 40px; }}
  h2 {{ color:#c4b5fd; }}
</style>
</head>
<body>
<header>
  <h1>{title}</h1>
  <p>Automated restoration &amp; analysis report generated by Book Restorer</p>
</header>
<div class="metrics">{metrics_html}</div>
<section class="text-block">
  <h2>Narrative Summary</h2>
  <p>{narrative_summary}</p>
  <h2>Sentiment Arc</h2>
  <p>{sentiment_arc}</p>
</section>
<div class="grid">{figures_html}</div>
</body>
</html>
"""


def _metric_card(value: str, label: str) -> str:
    return f'<div class="metric"><div class="value">{value}</div><div class="label">{label}</div></div>'


def build_html_report(
    output_path: Path,
    title: str,
    stats,
    narrative_summary: str,
    sentiment_arc: str,
    figures: Dict[str, "object"],
) -> Path:
    metrics_html = "".join([
        _metric_card(f"{stats.word_count:,}", "Words"),
        _metric_card(f"{stats.unique_word_count:,}", "Unique Words"),
        _metric_card(f"{stats.sentence_count:,}", "Sentences"),
        _metric_card(f"{stats.estimated_reading_minutes:.0f} min", "Est. Reading Time"),
        _metric_card(f"{stats.flesch_reading_ease:.1f}", "Flesch Reading Ease"),
        _metric_card(f"{stats.lexical_diversity:.2f}", "Lexical Diversity"),
    ])

    figures_html_parts = []
    for name, fig in figures.items():
        if fig is None:
            continue
        html_fragment = pio.to_html(fig, include_plotlyjs="cdn", full_html=False, config={"displaylogo": False})
        figures_html_parts.append(f'<div class="card">{html_fragment}</div>')

    html = _HTML_TEMPLATE.format(
        title=title,
        metrics_html=metrics_html,
        narrative_summary=narrative_summary or "N/A",
        sentiment_arc=sentiment_arc or "N/A",
        figures_html="".join(figures_html_parts),
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html, encoding="utf-8")
    return output_path


def build_pdf_report(
    output_path: Path,
    title: str,
    stats,
    chapters: List,
    insights,
    reference_stats: Dict,
    figures: Dict[str, "object"],
) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleStyle", parent=styles["Title"], textColor=colors.HexColor("#4c1d95"))
    h2_style = ParagraphStyle("H2Style", parent=styles["Heading2"], textColor=colors.HexColor("#6d28d9"))
    body_style = styles["BodyText"]

    doc = SimpleDocTemplate(str(output_path), pagesize=LETTER, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    story = []

    story.append(Paragraph(title, title_style))
    story.append(Paragraph("Automated Restoration &amp; Analysis Report", body_style))
    story.append(Spacer(1, 0.3 * inch))

    stats_table_data = [
        ["Words", f"{stats.word_count:,}"],
        ["Unique Words", f"{stats.unique_word_count:,}"],
        ["Sentences", f"{stats.sentence_count:,}"],
        ["Estimated Reading Time", f"{stats.estimated_reading_minutes:.0f} minutes"],
        ["Flesch Reading Ease", f"{stats.flesch_reading_ease:.1f}"],
        ["Flesch-Kincaid Grade", f"{stats.flesch_kincaid_grade:.1f}"],
        ["Lexical Diversity", f"{stats.lexical_diversity:.2f}"],
    ]
    table = Table(stats_table_data, colWidths=[3 * inch, 3 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#ede9fe")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#c4b5fd")),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(table)
    story.append(Spacer(1, 0.3 * inch))

    story.append(Paragraph("Narrative Summary", h2_style))
    story.append(Paragraph(insights.narrative_summary or "N/A", body_style))
    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph("Sentiment Arc", h2_style))
    story.append(Paragraph(insights.sentiment_arc_description or "N/A", body_style))
    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph("Key Themes", h2_style))
    story.append(Paragraph(", ".join(insights.themes) or "N/A", body_style))

    for name, fig in figures.items():
        png_bytes = fig_to_png_bytes(fig) if fig is not None else None
        if not png_bytes:
            continue
        story.append(PageBreak())
        story.append(Paragraph(name, h2_style))
        from io import BytesIO

        story.append(RLImage(BytesIO(png_bytes), width=6.2 * inch, height=3.7 * inch))

    story.append(PageBreak())
    story.append(Paragraph("Chapter Synopses", title_style))
    for chapter in chapters:
        story.append(Paragraph(f"Chapter {chapter.number}: {chapter.title}", h2_style))
        story.append(Paragraph(chapter.synopsis or "(No synopsis available)", body_style))
        story.append(Spacer(1, 0.2 * inch))

    story.append(PageBreak())
    story.append(Paragraph("Reference Highlights", title_style))
    for category, stat in reference_stats.items():
        story.append(Paragraph(f"{category.title()} References ({stat['total_matches']} matches)", h2_style))
        top_terms = ", ".join(f"{t} ({c})" for t, c in stat.get("top_terms", [])[:10])
        story.append(Paragraph(f"Top terms: {top_terms or 'None found'}", body_style))
        story.append(Spacer(1, 0.15 * inch))

    doc.build(story)
    return output_path
